kind = "web"
previewPath = "/"
title = "Oficinas Mecânicas"
version = "1.0.0"
id = "artifacts/oficinas-app"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19154

[services.development]
run = "pnpm --filter @workspace/oficinas-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/oficinas-app", "run", "build" ]
serve = "static"
publicDir = "artifacts/oficinas-app/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19154"
BASE_PATH = "/"
